version: '3'

services:
  db:
    hostname: mysql
    image: astondevops/docker-mysql-5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /var/log/mysql-db:/var/log/mysql
  phpmyadmin:
    hostname: phpmyadmin
    image: nazarpc/phpmyadmin
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
